
with open('src/App.js', encoding='utf-8') as f:
    lines = f.readlines()

# لاین 3261 دەگۆڕین
lines[3260] = '                  {editPaymentId ? (\n                  <div style={{ background: "#fff9e6", border: "1px solid #F59E0B", borderRadius: 8, padding: 10, marginBottom: 10 }}>\n                    <p style={{ fontSize: 12, color: "#D97706", marginBottom: 8, textAlign: "center", fontWeight: 600 }}>گۆڕینی پەرداخت</p>\n                    <div style={{ display: "flex", gap: 8, marginBottom: 8 }}>\n                      <input type="date" value={paymentDate} onChange={e => setPaymentDate(e.target.value)} style={{ flex: 1, padding: "8px", borderRadius: 6, border: "1px solid #e5e5e5", fontSize: 13, direction: "ltr" }} />\n                      <input type="number" value={paymentAmount} onChange={e => setPaymentAmount(e.target.value)} style={{ flex: 1, padding: "8px", borderRadius: 6, border: "1px solid #e5e5e5", fontSize: 13, direction: "ltr", textAlign: "center" }} />\n                    </div>\n                    <input placeholder="تێبینی" value={paymentNote} onChange={e => setPaymentNote(e.target.value)} style={{ width: "100%", padding: "8px", borderRadius: 6, border: "1px solid #e5e5e5", fontSize: 13, textAlign: "center", marginBottom: 8 }} />\n                    <div style={{ display: "flex", gap: 8 }}>\n                      <button onClick={() => { editPayment(paymentModal, editPaymentId, paymentAmount, paymentDate, paymentNote); setEditPaymentId(null); }} style={{ flex: 1, background: "#F59E0B", color: "#fff", border: "none", borderRadius: 6, padding: "8px", fontSize: 13, fontWeight: 700, cursor: "pointer" }}>گۆڕین</button>\n                      <button onClick={() => { setEditPaymentId(null); setPaymentAmount(""); setPaymentDate(today()); setPaymentNote(""); }} style={{ flex: 1, background: "#f5f5f5", color: "#333", border: "1px solid #e5e5e5", borderRadius: 6, padding: "8px", fontSize: 13, cursor: "pointer" }}>پاشگەزبوونەوە</button>\n                    </div>\n                  </div>\n                  ) : null}\n                  {!item.isReceived && (\n'

with open('src/App.js', 'w', encoding='utf-8') as f:
    f.writelines(lines)
print('done!')
