code = []
code.append('import { useEffect, useRef } from "react";')
code.append('import { supabase } from "./supabase";')
code.append('function getLS(k) { try { var v = JSON.parse(localStorage.getItem(k)); return Array.isArray(v) ? v : []; } catch(e) { return []; } }')
code.append('function N(v) { return Number(v) ? Number(v) : 0; }')
code.append('function S(v) { return v ? String(v) : ""; }')
code.append('function B(v) { return v ? true : false; }')
code.append('export default function AutoSync({ project, cashIQD, cashUSD, exchangeRate, users }) {')
code.append('  const lastHash = useRef("");')
code.append('  useEffect(() => {')
code.append('    if (!project) return;')
code.append('    const doSync = async () => {')
code.append('      try {')
code.append('        var exp = getLS("karo_exp_" + project);')
code.append('        var conc = getLS("karo_conc_" + project);')
code.append('        var uLen = users ? users.length : 0;')
code.append('        var hash = exp.length + "_" + conc.length + "_" + cashIQD + "_" + cashUSD + "_" + uLen + "_" + Math.floor(Date.now()/5000);')
code.append('        if (hash === lastHash.current) return;')
code.append('        lastHash.current = hash;')
code.append('        await supabase.from("expenses").delete().eq("project", project);')
code.append('        if (exp.length > 0) {')
code.append('          var rows = [];')
code.append('          for (var i = 0; i < exp.length; i++) {')
code.append('            var e = exp[i];')
code.append('            rows.push({ id: e.id, project: project, date: e.date, amountiqd: N(e.amountIQD), amountusd: N(e.amountUSD), receiptno: S(e.receiptNo), note: S(e.note), marked: B(e.marked) });')
code.append('          }')
code.append('          await supabase.from("expenses").upsert(rows);')
code.append('        }')
code.append('        await supabase.from("concrete").delete().eq("project", project);')
code.append('        if (conc.length > 0) {')
code.append('          var rows2 = [];')
code.append('          for (var i = 0; i < conc.length; i++) {')
code.append('            var c = conc[i];')
code.append('            rows2.push({ id: c.id, project: project, date: c.date, currency: S(c.currency) ? S(c.currency) : "iqd", meters: N(c.meters), pricepermeter: N(c.pricePerMeter), totalprice: N(c.totalPrice), deposit: N(c.deposit), depositpercent: N(c.depositPercent), received: N(c.received), isreceived: B(c.isReceived), depositclaimed: B(c.depositClaimed), note: S(c.note), marked: B(c.marked) });')
code.append('          }')
code.append('          await supabase.from("concrete").upsert(rows2);')
code.append('        }')
code.append('        await supabase.from("cash").upsert([{ id: project, project: project, cashiqd: cashIQD, cashusd: cashUSD, exchangerate: exchangeRate }]);')
code.append('        if (users && users.length > 0) {')
code.append('          for (var i = 0; i < users.length; i++) {')
code.append('            var u = users[i];')
code.append('            await supabase.from("users").upsert([{ username: u.username, password: u.password, project: u.project, label: u.label, isadmin: B(u.isAdmin), isfrozen: B(u.isFrozen) }]);')
code.append('          }')
code.append('          var dbUsers = await supabase.from("users").select("username");')
code.append('          if (dbUsers.data) {')
code.append('            var localNames = users.map(function(u) { return u.username; });')
code.append('            for (var i = 0; i < dbUsers.data.length; i++) {')
code.append('              if (localNames.indexOf(dbUsers.data[i].username) === -1) {')
code.append('                await supabase.from("users").delete().eq("username", dbUsers.data[i].username);')
code.append('              }')
code.append('            }')
code.append('          }')
code.append('        }')
code.append('        console.log("Synced:", project);')
code.append('      } catch(err) { console.error("Sync error:", err); }')
code.append('    };')
code.append('    doSync();')
code.append('    var interval = setInterval(doSync, 5000);')
code.append('    return () => clearInterval(interval);')
code.append('  }, [project, cashIQD, cashUSD, exchangeRate, users]);')
code.append('  return null;')
code.append('}')

f = open('src/AutoSync.js', 'w', encoding='utf-8')
f.write('\n'.join(code) + '\n')
f.close()
print("AutoSync v5 done!")